### ISSUE TITLE
read_tau_amf failure with new UGWPV1 parameters

### ISSUE THREAD

**Issue by dpsarmie** [ufs-community/ccpp-physics#224]
# Description

The following error occurs in UFS when running the `control_c48` regression test with the `gnu` compiler on Hera:

> 5: FATAL from PE     5: Call to CCPP physics_init step failed
> 5:
> 1: An error occurred in ccpp_physics_init
> 1: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message

The error does not occur when compiling with the intel compiler. The error also does not occur when running on other platforms with the gnu compiler.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Updated version of UFS that causes the issue is here: https://github.com/ufs-community/ufs-weather-model/pull/2363
2. Run the UFS regression test `./rt.sh -a <account> -n "control_c48 gnu"` on Hera
3. Run will crash with the above error.

## Additional Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Hera, control_c48 regression test
* gnu compiler

## Output
[...]
> + PSM_RANKS_PER_CONTEXT=4
> + export PSM_SHAREDCONTEXTS=1
> + PSM_SHAREDCONTEXTS=1
> + sync
> + sleep 1
> + '[' NO = WHEN_RUNNING ']'
> + srun --label -n 8 ./fv3.exe
> 5: An error occurred in ccpp_physics_init
> 5: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message
> 5:
> 5: FATAL from PE     5: Call to CCPP physics_init step failed
> 5:
> 1: An error occurred in ccpp_physics_init
> 1: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message
> 1:
> 1: FATAL from PE     1: Call to CCPP physics_init step failed
> 1:
> 3: An error occurred in ccpp_physics_init
> 3: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message
> 3:
> 3: FATAL from PE     3: Call to CCPP physics_init step failed
> 3:
> 4: An error occurred in ccpp_physics_init
> 4: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message
> 4:
> 4: FATAL from PE     4: Call to CCPP physics_init step failed
> 4:
> 2: An error occurred in ccpp_physics_init
> 2: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message
> 2:
> 2: FATAL from PE     2: Call to CCPP physics_init step failed
> 2:
> 0: An error occurred in ccpp_physics_init
> 0: An error occured in GFS_phys_time_vary_init: read_tau_amf failed without a message
> 0:
> 0: FATAL from PE     0: Call to CCPP physics_init step failed
> 0:
> 0: #0  0x1a49aee in ???
> 1: #0  0x1a49aee in ???
> 2: #0  0x1a49aee in ???

**Comment by dpsarmie** [comment]
Clean up. This issue was resolved a while ago.
